### ISSUE TITLE
Add Contact Us Page

### ISSUE THREAD

**Issue by LJSkinner** [LJSkinner/Uni-Stirling-Grade-Calculator-Website#12]
The Contact Us page was discussed in #3 and although not as high priority as the calculator pages, should be relatively easy to implement.

**Comment by LJSkinner** [comment]
@AndrewMcGuckin 

If you're making another wireframe, plop it in here as well as in #3 just so that it's all together. 👍

**Comment by LJSkinner** [comment]
@AndrewMcGuckin 

Had a quick look at the actual commits you had made. Looking pretty good. What do you have in mind for making this responsive? Are we dropping the picture on smaller screens or making it more like a banner?

**Comment by AndrewMcGuckin** [comment]
> @AndrewMcGuckin
> 
> If you're making another wireframe, plop it in here as well as in #3 just so that it's all together. 👍

### Contact Wireframe

A simple but clear contact page to allow a user to contact us quickly either through a contact form or by emailing us directly.

![Grade Calculator-Contact](https://user-images.githubusercontent.com/50446517/211615930-74ab9223-5b67-412f-8b2d-51acb107f134.png)

As mentioned above by @LJSkinner, this has also been put into #3.

**Comment by AndrewMcGuckin** [comment]
> @AndrewMcGuckin
> 
> Had a quick look at the actual commits you had made. Looking pretty good. What do you have in mind for making this responsive? Are we dropping the picture on smaller screens or making it more like a banner?

@LJSkinner 
I think a banner would look quite nice, however with the information that is included on the picture it could just resize to stack each section with the image first then the contact form further down.

**Comment by LJSkinner** [comment]
> > @AndrewMcGuckin
> > Had a quick look at the actual commits you had made. Looking pretty good. What do you have in mind for making this responsive? Are we dropping the picture on smaller screens or making it more like a banner?
> 
> @LJSkinner I think a banner would look quite nice, however with the information that is included on the picture it could just resize to stack each section with the image first then the contact form further down.

@AndrewMcGuckin 

I've had a look at the recent commits you've made. I think this page is now at a stage that it can be merged with main. Making the form actually work is something for much later. So go ahead and make a pull request, unless you have other things planned for the Contact Us Page.
