### ISSUE TITLE
Add FAQ Page

### ISSUE THREAD

**Issue by LJSkinner** [LJSkinner/Uni-Stirling-Grade-Calculator-Website#16]
The FAQ page was discussed in #3. This like the Contact Page is not as crucial as the calculator pages but is something that can be worked on alongside other work.

**Comment by LJSkinner** [comment]
@AndrewMcGuckin 

Had a quick look at your recent commits. This is looking good. Only thing that I noticed, which I assume will change, is the FAQ title being centred the way it is. 

Here's some things we absolutely want in the FAQ to help you as you're building it (you can reword these if you want):

**Q: Any boring legal stuff I should know about this website?**
A: Yes actually. We're not being paid or serviced by the University to create this website, this is being created in our free time as a self project. We maintain this website ourselves and thus at any point we could seize production. Our website is not affiliated with University of Stirling in any way, and is not representative of their views or values. This calculator is also not a 100% accurate fool proof estimate of your grades, and so you should use this as a guide and not a rule. We don't take any responsibility for your classification/grades being inaccurate to what you receive. 

**Q: Does this website use grade information for anything other than calculating degrees/module results?**
A: Absolutely not. Although we plan to implement functionality to allow you to store your grade info for later use, this is only being used for your benefit and nothing else. We would never sell on other peoples data. All of our source code is public and you're free to check this yourself.

**Q: How accurate is this calculator at calculating my scores/degree classification?**
A: We try to be as accurate as possible to the specification which is laid out by the University, but we of course can't totally predict the algorithm, and the rules could change over time. You should take this as a guide, and redirect any serious grade questions to your Chief Examiner or Personal Tutor.

**Q: What about dual programs or more complex degree structures?**
A: Unfortunately, we're unable to reliably cover all of these as they would have many exceptions to the normal calculation rules. You should still be able to attempt to calculate your classification, but it is not as reliable as a normal program.

**Comment by AndrewMcGuckin** [comment]
@LJSkinner 

I've updated the design of the page, I'm not sure if I like the background colour just yet but I think it's an improvement. I've also added the questions and answers that you posted above.

**Comment by LJSkinner** [comment]
> @LJSkinner
> 
> I've updated the design of the page, I'm not sure if I like the background colour just yet but I think it's an improvement. I've also added the questions and answers that you posted above.

@AndrewMcGuckin 

Hm. I'm not totally opposed to this. Have you tried how this would look with a second border around the white one. Perhaps a lighter gray or something like that with the blue background?

**Comment by AndrewMcGuckin** [comment]
> > @LJSkinner
> > I've updated the design of the page, I'm not sure if I like the background colour just yet but I think it's an improvement. I've also added the questions and answers that you posted above.
> 
> @AndrewMcGuckin
> 
> Hm. I'm not totally opposed to this. Have you tried how this would look with a second border around the white one. Perhaps a lighter gray or something like that with the blue background?

@LJSkinner 
Here's a few variations based on this, what are your thoughts?

#### 1. Light gray border-8 with 2xl shadow
![image](https://user-images.githubusercontent.com/50446517/212408778-2a54c391-ca13-4dc5-97ee-dd5967fcc9d6.png)

#### 2. Light background with dark border-8 and 2xl shadow
![image](https://user-images.githubusercontent.com/50446517/212409371-3fe3044f-1b88-46f9-95b7-ad9fa0f7914e.png)

#### 3. Light background with blue to green gradient
![image](https://user-images.githubusercontent.com/50446517/212410783-7fffd900-74c1-48e9-b7f6-296dee9df11d.png)
Note: adjusted the colours on this one to show the effect better

Personally I really like 3, the gradient gives it something different but I feel that it doesn't match what we are going for and the darker colours in our palette aren't very noticeable when applied, hence why I applied lighter colours. I'm torn between 1 & 2 because I like the darker background but the gray border doesn't blend as well compared to how the dark blue does in 2.

**Comment by LJSkinner** [comment]
> > > @LJSkinner
> > > I've updated the design of the page, I'm not sure if I like the background colour just yet but I think it's an improvement. I've also added the questions and answers that you posted above.
> > 
> > 
> > @AndrewMcGuckin
> > Hm. I'm not totally opposed to this. Have you tried how this would look with a second border around the white one. Perhaps a lighter gray or something like that with the blue background?
> 
> @LJSkinner Here's a few variations based on this, what are your thoughts?
> #### 1. Light gray border-8 with 2xl shadow
> 
> ![image](https://user-images.githubusercontent.com/50446517/212408778-2a54c391-ca13-4dc5-97ee-dd5967fcc9d6.png)
> #### 2. Light background with dark border-8 and 2xl shadow
> 
> ![image](https://user-images.githubusercontent.com/50446517/212409371-3fe3044f-1b88-46f9-95b7-ad9fa0f7914e.png)
> #### 3. Light background with blue to green gradient
> 
> ![image](https://user-images.githubusercontent.com/50446517/212410783-7fffd900-74c1-48e9-b7f6-296dee9df11d.png) Note: adjusted the colours on this one to show the effect better
> 
> Personally I really like 3, the gradient gives it something different but I feel that it doesn't match what we are going for and the darker colours in our palette aren't very noticeable when applied, hence why I applied lighter colours. I'm torn between 1 & 2 because I like the darker background but the gray border doesn't blend as well compared to how the dark blue does in 2.

@AndrewMcGuckin 

Hm. I'm curious how 1 would look with more of a shadow, and I do like the gradient as well.  I feel like we may have to do a "style check" once we get further on with this project, where by we go through each page and make sure they all fit with the style. I think for now just go with what you think is best, since this page is not as crucial as our undergrad stuff. Good work though.

**Comment by LJSkinner** [comment]
@AndrewMcGuckin 

I've had a look at this again. Of course it's up to you if you want to make any additional changes, but I think this page is fine for now and is at a stage where it could be merged. Feel free to make a pull request at your leisure and I'll give it another look over.
